Correction défaut intégration continue (icon)

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -1,6 +1,7 @@
 name: CPP-COSO
 
 on:
+  workflow_dispatch:
   schedule:
     - cron: '1 1 1 * *'
   push:
@@ -12,8 +13,8 @@ on:
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Release
-  BOOST_VERSION: 1.79.0
-  APPLICATION_VERSION: 0.2.1
+  BOOST_VERSION: 1.81.0
+  APPLICATION_VERSION: 0.2.2
   APPLICATION_NAME: cpp-coso
 
 permissions: write-all
@@ -47,16 +48,19 @@ jobs:
         fetch-depth: 0
 
     - name: Install dependencies
-      run: sudo apt-get install -y clang-tidy cppcheck doxygen graphviz inkscape imagemagick
-
+      run: |
+        sudo add-apt-repository ppa:inkscape.dev/stable
+        sudo apt update  
+        sudo apt-get install -y doxygen graphviz clang-tidy clang-format cppcheck imagemagick inkscape
+      
     - name: Create icon
       working-directory: ${{github.workspace}}/resources/icon/cpp-coso
       run: |
-        dbus-run-session inkscape -w 16 -h 16 -e cpp-coso-16x16.png cpp-coso.svg
-        dbus-run-session inkscape -w 32 -h 32 -e cpp-coso-32x32.png cpp-coso.svg
-        dbus-run-session inkscape -w 48 -h 48 -e cpp-coso-48x48.png cpp-coso.svg
-        dbus-run-session inkscape -w 256 -h 256 -e cpp-coso-256x256.png cpp-coso.svg
-        dbus-run-session inkscape -e cpp-coso.bmp cpp-coso.svg
+        dbus-run-session inkscape -w 16 -h 16 --export-type=png --export-filename=cpp-coso-16x16.png cpp-coso.svg
+        dbus-run-session inkscape -w 32 -h 32 --export-type=png --export-filename=cpp-coso-32x32.png cpp-coso.svg
+        dbus-run-session inkscape -w 48 -h 48 --export-type=png --export-filename=cpp-coso-48x48.png cpp-coso.svg
+        dbus-run-session inkscape -w 256 -h 256 --export-type=png --export-filename=cpp-coso-256x256.png cpp-coso.svg
+        # dbus-run-session inkscape -e cpp-coso.bmp cpp-coso.svg
         convert cpp-coso-16x16.png cpp-coso-32x32.png cpp-coso-48x48.png cpp-coso-256x256.png cpp-coso.ico
 
     - name: Save icon changes
@@ -154,7 +158,7 @@ jobs:
       run: sonar-scanner
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}
         -Dsonar.host.url=https://sonarcloud.io/
-        -Dsonar.verbose=false
+        -Dsonar.verbose=true
 
     # - name: SonarQube Quality Gate check
     #   uses: sonarsource/sonarqube-quality-gate-action@master
@@ -237,8 +241,7 @@ jobs:
  build-debug-Windows:
     env:
       BUILD_TYPE: Debug
-      BOOST_VERSION: 1.79.0
-
+      
     runs-on: windows-latest
     steps:
 
@@ -280,8 +283,6 @@ jobs:
 
  build-release-Windows:
     needs: [build-debug-Windows]
-    env:
-      BOOST_VERSION: 1.79.0
 
     if: ${{github.head_ref}} == 'main' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
     runs-on: windows-latest
@@ -454,7 +455,9 @@ jobs:
       run: git checkout delivery --
 
     - name: check version is not duplicated
-      run: ([ -d "./delivery/${{env.APPLICATION_VERSION}}" ] && (echo "Error the version ${{env.APPLICATION_VERSION}} already exist in repository" && exit 1) || echo "The version number is available, prepare publish...")
+      run: |
+        ([ -d "./delivery/${{env.APPLICATION_VERSION}}" ] && (echo "Error the version ${{env.APPLICATION_VERSION}} already exist in repository" && exit 1)
+        echo "The version number is available, prepare publish...")
 
     - name: Download docs
       uses: actions/download-artifact@v3
